# Generated by Django 2.1.6 on 2019-02-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190211_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='customers',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Customers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='profession',
            field=models.ManyToManyField(to='core.Profession'),
        ),
    ]
