# Generated by Django 2.1.6 on 2019-02-11 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190211_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('historical_data', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='data_sheet',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.DataSheet'),
            preserve_default=False,
        ),
    ]
