# Generated by Django 2.1.6 on 2019-02-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190211_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
